// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY5Pha1ZIN_P_a5maVnNqHVd_ZDj3NKp0',
    appId: '1:767221750547:web:a5de209ae316751d55d8e6',
    messagingSenderId: '767221750547',
    projectId: 'iot1-55f24',
    authDomain: 'iot1-55f24.firebaseapp.com',
    databaseURL: 'https://iot1-55f24-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-55f24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86RePSXT3A3ZdMA8CbMK2FNjxwYZUT9E',
    appId: '1:767221750547:android:edac04d742f7925955d8e6',
    messagingSenderId: '767221750547',
    projectId: 'iot1-55f24',
    databaseURL: 'https://iot1-55f24-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-55f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLwWLHvaYlGRalX64D_8wK-xvDyyMulH4',
    appId: '1:767221750547:ios:8ca5cbd7d5fb9dba55d8e6',
    messagingSenderId: '767221750547',
    projectId: 'iot1-55f24',
    databaseURL: 'https://iot1-55f24-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-55f24.appspot.com',
    iosClientId: '767221750547-btjcid2rm1ija0qa6n1rpso6p3mml1ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.baggageTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLwWLHvaYlGRalX64D_8wK-xvDyyMulH4',
    appId: '1:767221750547:ios:8ca5cbd7d5fb9dba55d8e6',
    messagingSenderId: '767221750547',
    projectId: 'iot1-55f24',
    databaseURL: 'https://iot1-55f24-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-55f24.appspot.com',
    iosClientId: '767221750547-btjcid2rm1ija0qa6n1rpso6p3mml1ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.baggageTracker',
  );
}
